###
### Create an instance in OpenStack
###
---
- hosts: localhost
  gather_facts: false
  vars:
    host_name: test1
    os_config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"
    os_auth:
      project_name: "{{ lookup('env', 'OS_PROJECT') }}"
      auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
      username: "{{ lookup('env', 'OS_USERNAME') }}"
      password: "{{ lookup('env', 'OS_PASSWORD') }}"

  tasks:
    - name: Load Tower cloud credential config when it is present
      include_vars: "{{ os_config_file }}"
      when: os_config_file != ''

    - name: Set necessary variables when Tower cloud credential config is present
      set_fact:
        os_auth:
          auth_url: "{{ clouds.devstack.auth.auth_url }}"
          username: "{{ clouds.devstack.auth.username }}"
          password: "{{ clouds.devstack.auth.password }}"
          project_name: "{{ clouds.devstack.auth.project_name }}"
      when: os_config_file != ''

    - name: Fail if fallback environment variables are not set
      fail:
        msg: "missing required environment variable: '{{ item }}'"
      when: os_config_file == '' and lookup('env', item) is undefined
      with_items:
        - OS_AUTH_URL
        - OS_USERNAME
        - OS_PASSWORD
        - OS_PROJECT

    - name: Create a new instance and attaches to a network
      os_server:
        auth: "{{ os_auth }}"
        state: present
        name: "{{ host_name }}"
        image: CentOS-7-1809
        key_name: demo
        security_groups: default
        timeout: 200
        flavor: m1.small
        config_drive: yes
        network: public
        auto_ip: no
        meta:
          hostname: "{{ host_name }}"
