---
- hosts: all

  tasks:
    - name: Install httpd & git
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - httpd
        - git

    - name: Starting httpd service
      systemd:
        name: httpd
        state: started
        enabled: yes
