---
- hosts: all
  tasks:
    - name: Register a system to Red Hat
      redhat_subscription:
        state: present
        username: hirotada.sasaki
        password: ls!9Ev-3nOqU
        pool: 8a85f9815de88240015de93c42c9209a

    - name: Configure repository
      yum_repository:
        name: rhel-7-server-rpms
        description: Red Hat Enterprise Linux 7 Server (RPMs)
        baseurl: https://cdn.redhat.com/content/dist/rhel/server/7/$releasever/$basearch/os
