---
- hosts: all
  tasks:
    - name: Register a system to Red Hat
      redhat_subscription:
        state: present
        username: hirotada.sasaki
        password: ls!9Ev-3nOqU
        pool: 8a85f9815de88240015de93c42c9209a

    - name: Configure repository
      yum_repository:
        name: rhel-7-server-rpms
        description: Red Hat Enterprise Linux 7 Server (RPMs)
        baseurl: https://cdn.redhat.com/content/dist/rhel/server/7/$releasever/$basearch/os

    - name: Disabling unnecessary repos
      yum_repository:
        name: "{{ repo_name }}"
        enabled: no
        with_items: [ rhel-7-server-htb-rpms, rhel-7-server-tus-rpms, rhel-7-rc-rpms, rhel-7-server-aus-rpms, rhel-7-server-nfv-rpms, rhel-7-server-rt-htb-rpms rhel-7-server-rt-rpms, rhel-7-server-rt-beta-rpms ]
